<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta property="og:title" content="Your Subject goes here">
		<title><?php echo $this->company; ?></title>
        <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true&amp;skin=sunburst&amp;lang=css" defer="defer"></script>
    </head>
    <body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="-webkit-text-size-adjust: none;margin: 0;padding: 0;background-color: #FFFFFF;width: 100%; ">
        <?php echo $this->content; ?>
        <style type="text/css">
            @media only screen and (max-width: 480px) {
                #canspamBar {
                    display: inline;
                }
                #canspamBar td {
                    display: block;
                    margin: 0 0 10px 0;
                }
            }
        </style>
    </body>
</html>