<?php

namespace App\Repository;

/**
 * CardChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardChannelRepository extends \Doctrine\ORM\EntityRepository
{
}
