<?php

namespace App\Repository;

/**
 * PaygateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaygateRepository extends \Doctrine\ORM\EntityRepository
{
}
