Chào bạn <?php echo $this->username;?>
<br/>

<p>Bạn vừa yêu cầu lấy lại mật khẩu của tài khoản: <?php echo $this->username;?></p>
<p>Mã xác thực của bạn là: <?php echo $this->code;?></p>
<p>Truy cập địa chỉ dưới đây để hoàn tất việc lấy lại mật khẩu: </p>
<a href="https://<?php echo $_SERVER['HTTP_HOST'];?>/lay-lai-mat-khau/email">
    https://<?php echo $_SERVER['HTTP_HOST'];?>/lay-lai-mat-khau/email
</a>