<link href="/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
<div class="container">
	<div class="page-header"><h1>Error Messages Info</h1></div>
	<pre class="prettyprint"><?php echo $this->message;?></pre>
    <br/><br/><hr/>
    <div class="page-header"><h1>BackTrace::</h1></div>
    <?php echo $this->backtrace;?>
    <br/><br/><hr/>
    <div class="page-header"><h1>Server Info</h1></div>
    <br/>
    <table class="table table-striped table-bordered table-hover table-condensed prettyprint">
        <tbody>
        <?php foreach ($this->serverInfo as $key => $value) :?>
            <tr>
                <td><?php echo $key;?></td>
                <td><?php echo $value;?></td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>
